os: linux
dist: xenial
language: php

services:
    - docker

before_script:
    - docker build -t amqp-bundle .
    - docker run -it -d --name amqp-bundle amqp-bundle

script:
    - sed 's/.*symfony\/dependency-injection.*/"symfony\/dependency-injection":"~5.0",/' composer.json > composer.json
    - sed 's/.*symfony\/framework-bundle.*/"symfony\/framework-bundle": "~5.0"/' composer.json > composer.json

    - docker cp . amqp-bundle:/code
    - docker exec amqp-bundle composer update --prefer-stable
    - docker exec amqp-bundle bin/phpcs --config-set show_warnings 0
    - docker exec amqp-bundle bin/phpcs --standard=vendor/escapestudios/symfony2-coding-standard/Symfony/ src/
    - docker exec amqp-bundle bin/phpcs --standard=tests/phpcs-ruleset.xml tests/

    # Test on SF 5
    - docker exec amqp-bundle bin/phpunit
    - docker exec amqp-bundle composer update --prefer-lowest
    - docker exec amqp-bundle bin/phpunit

    # Test on SF 4
    - sed 's/.*symfony\/dependency-injection.*/"symfony\/dependency-injection":"~4.0",/' composer.json > composer.json
    - sed 's/.*symfony\/framework-bundle.*/"symfony\/framework-bundle": "~4.0"/' composer.json > composer.json
    - docker exec amqp-bundle composer update --prefer-stable
    - docker exec amqp-bundle bin/phpunit
    - docker exec amqp-bundle composer update --prefer-lowest
    - docker exec amqp-bundle bin/phpunit

    # Test on SF 3
    - sed 's/.*symfony\/dependency-injection.*/"symfony\/dependency-injection":"~3.0",/' composer.json > composer.json
    - sed 's/.*symfony\/framework-bundle.*/"symfony\/framework-bundle": "~3.0"/' composer.json > composer.json
    - docker exec amqp-bundle composer update --prefer-stable
    - docker exec amqp-bundle bin/phpunit
    - docker exec amqp-bundle composer update --prefer-lowest
    - docker exec amqp-bundle bin/phpunit

after_script:
    - docker kill $(docker ps -q)
    - docker rm $(docker ps -a -q)
